<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/assets/cute_bunny.glb
Author: Ndevisuals (https://sketchfab.com/Wade23)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-bunny-037f632eb1cc45889219629187df68db
Title: Cute Bunny
-->

<script lang="ts">
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/assets/cute_bunny.glb')

  const component = forwardEventHandlers()

  import { Color, MeshPhysicalMaterial, type BufferGeometry } from 'three'
  import { onDestroy } from 'svelte'
  const body = new Color(0xFFFFFF)
  const eye = new Color(0x219FDA)
  let material1 = new MeshPhysicalMaterial({
    color: body,
    reflectivity: 1,
    metalness: 0.9,
    roughness: 0
  })

  let material2 = new MeshPhysicalMaterial({
    color: eye,
    reflectivity: .2,
    metalness: 0.9,
    roughness: 0.2
  })
  onDestroy(() => {
    material1.dispose(),
    material2.dispose()

  })

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Object_4.geometry} 
      material={material1}
      scale={2}

    />
    <T.Mesh geometry={gltf.nodes.Object_5.geometry} 
      material={material2} 
      scale={2}

    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
