<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./src/egg.glb
Author: Pylimas (https://sketchfab.com/Pylimas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/easter-egg-with-flower-2666487372854a83ae94c70f414b1560
Title: Easter egg with flower
-->

<script lang="ts">
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/assets/egg.glb')

  const component = forwardEventHandlers()

  import { Color, MeshPhysicalMaterial, type BufferGeometry } from 'three'
  import { onDestroy } from 'svelte'
  const red = new Color(0xfe3d00)
  const blue = new Color(0x0000ff)
  let material = new MeshPhysicalMaterial({
    color: red,
    reflectivity: 1,
    metalness: 0.9,
    roughness: 0.2
  })
  onDestroy(() => {
    material.dispose()
  })

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Mesh
        geometry={gltf.nodes.Sphere_Material001_0.geometry}
        material={material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={90}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
