<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/assets/moai_mountain.glb
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moai-mountain-2536e27e59cb41eeaf57376d23009a92
Title: moai mountain
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/assets/moai_mountain.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={.9}>
      <T.Group position={[140, -25.04, -51.3]} rotation={[0, -0.1, 0]}>
        <T.Group position={[-134.46, 25.04, 64.43]} rotation={[0, 0.1, 0]}>
          <T.Group position={[2611.8, 0, -4.01]} scale={10}>
            <T.Mesh
              geometry={gltf.nodes.island_basemodel_02_driveable_grass_0.geometry}
              material={gltf.materials.grass}
            />
            <T.Mesh
              geometry={gltf.nodes['island_basemodel_02_driveable_Grass-Sand_0'].geometry}
              material={gltf.materials['Grass-Sand']}
            />
            <T.Mesh
              geometry={gltf.nodes.island_basemodel_02_driveable_sandwall_0.geometry}
              material={gltf.materials.sandwall}
            />
          </T.Group>
          <T.Group position={[2611.8, 0, -4.01]} scale={10}>
            <T.Mesh geometry={gltf.nodes.island_basemodel_03_sand_sand_0.geometry} material={gltf.materials.sand} />
            <T.Mesh
              geometry={gltf.nodes.island_basemodel_03_sand_Beachsand_0.geometry}
              material={gltf.materials.Beachsand}
            />
          </T.Group>
          <T.Group position={[2611.8, 0, -4.01]} scale={10}>
            <T.Mesh geometry={gltf.nodes.island_basemodel_04_sand_sand_0.geometry} material={gltf.materials.sand} />
            <T.Mesh
              geometry={gltf.nodes.island_basemodel_04_sand_Beachsand_0.geometry}
              material={gltf.materials.Beachsand}
            />
          </T.Group>
          <T.Group position={[2611.8, 0, -4.01]} scale={10}>
            <T.Mesh
              geometry={gltf.nodes['island_basemodel_04_driveable_Grass-Sand_0'].geometry}
              material={gltf.materials['Grass-Sand']}
            />
            <T.Mesh
              geometry={gltf.nodes.island_basemodel_04_driveable_grass_0.geometry}
              material={gltf.materials.grass}
            />
          </T.Group>
          <T.Group position={[2611.8, 0, -4.01]} scale={10}>
            <T.Mesh
              geometry={gltf.nodes.tutorial_road_stone_pavement_0.geometry}
              material={gltf.materials.stone_pavement}
            />
            <T.Mesh geometry={gltf.nodes.tutorial_road_GravelRoad_0.geometry} material={gltf.materials.GravelRoad} />
            <T.Mesh
              geometry={gltf.nodes.tutorial_road_02_stone_pavement_0.geometry}
              material={gltf.materials.stone_pavement}
            />
            <T.Mesh geometry={gltf.nodes.tutorial_road_02_GravelRoad_0.geometry} material={gltf.materials.GravelRoad} />
            <T.Mesh
              geometry={gltf.nodes.tutorial_road_03_stone_pavement_0.geometry}
              material={gltf.materials.stone_pavement}
            />
            <T.Mesh geometry={gltf.nodes.tutorial_road_03_GravelRoad_0.geometry} material={gltf.materials.GravelRoad} />
            <T.Mesh geometry={gltf.nodes.tutorial_road_03_Pillar_0.geometry} material={gltf.materials.Pillar} />
            <T.Mesh
              geometry={gltf.nodes.tutorial_road_04_stone_pavement_0.geometry}
              material={gltf.materials.stone_pavement}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes.island_basemodel_driveable_grass_0.geometry}
            material={gltf.materials.grass}
            position={[2611.8, 0, -4.01]}
            scale={10}
          />
          <T.Mesh
            geometry={gltf.nodes.island_cave_sand_sand_0.geometry}
            material={gltf.materials.sand}
            position={[2611.8, 0, -4.01]}
            scale={10}
          />
          <T.Mesh
            geometry={gltf.nodes.rope_bridge_driveable_rope_bridge_0.geometry}
            material={gltf.materials.rope_bridge}
            position={[2611.8, 0, -4.01]}
            scale={10}
          />
        </T.Group>
        <T.Group position={[556.15, 70.04, 728.67]} rotation={[0, 0.1, 0]}>
          <T.Mesh
            geometry={gltf.nodes.Cube_StoneCarving3_0.geometry}
            material={gltf.materials.StoneCarving3}
            position={[56.63, -33.36, 5.38]}
            rotation={[0, 1.37, Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(1)_StoneCarving1_0'].geometry}
            material={gltf.materials.StoneCarving1}
            position={[-41.84, -25.17, 186.24]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(2)_StoneCarving2_0'].geometry}
            material={gltf.materials.StoneCarving2}
            position={[25.32, 4.18, 191.69]}
            rotation={[0, 0, 0.76]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(3)_broken_cobbles1_0'].geometry}
            material={gltf.materials.broken_cobbles1}
            position={[16.86, -35.14, -75.34]}
            rotation={[Math.PI / 2, 0, 2.59]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(4)_broken_cobbles2_0'].geometry}
            material={gltf.materials.broken_cobbles2}
            position={[10.66, -36.35, -49.55]}
            rotation={[Math.PI / 2, 0, 2.62]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(5)_broken_cobbles2_0'].geometry}
            material={gltf.materials.broken_cobbles2}
            position={[219.68, -34.87, 317.11]}
            rotation={[Math.PI / 2, 0, -3.12]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(6)_StoneCarving1_0'].geometry}
            material={gltf.materials.StoneCarving1}
            position={[229.74, -28.74, 308.25]}
            rotation={[-Math.PI, 1.39, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(7)_StoneCarving1_0'].geometry}
            material={gltf.materials.StoneCarving1}
            position={[-24.52, -25.77, -130.78]}
            rotation={[2.42, -1.25, -2.27]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(8)_StoneCarving2_0'].geometry}
            material={gltf.materials.StoneCarving2}
            position={[-26.26, -28.16, -100.58]}
            rotation={[1.27, -1.2, 2.26]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(9)_FlowerDecal2_0'].geometry}
            material={gltf.materials.FlowerDecal2}
            position={[42.63, -28.42, -111.13]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(10)_FlowerDecal2_0'].geometry}
            material={gltf.materials.FlowerDecal2}
            position={[246.8, -26.41, -18.44]}
            rotation={[Math.PI / 2, 0, 0.91]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(11)_FlowerDecal2_0'].geometry}
            material={gltf.materials.FlowerDecal2}
            position={[452.07, -25.51, -25.97]}
            rotation={[Math.PI / 2, 0, 1.96]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(12)_broken_cobbles2_0'].geometry}
            material={gltf.materials.broken_cobbles2}
            position={[409.18, -25.49, -67.54]}
            rotation={[Math.PI / 2, 0, 1.21]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(13)_broken_cobbles1_0'].geometry}
            material={gltf.materials.broken_cobbles1}
            position={[179.78, -27.43, -74.16]}
            rotation={[Math.PI / 2, 0, -2.9]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(14)_StoneCarving3_0'].geometry}
            material={gltf.materials.StoneCarving3}
            position={[268.46, -18.63, -7.85]}
            rotation={[0, -0.03, Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(15)_stone_0'].geometry}
            material={gltf.materials.stone}
            position={[20.08, -36.16, 240.05]}
            rotation={[Math.PI / 2, 0, 0.79]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(16)_stone_0'].geometry}
            material={gltf.materials.stone}
            position={[-14.02, -39.25, 95.04]}
            rotation={[Math.PI / 2, 0, 0.79]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(17)_Rocks2_0'].geometry}
            material={gltf.materials.Rocks2}
            position={[224.59, -34.57, -87.53]}
            rotation={[Math.PI / 2, 0, 2.31]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(19)_stone_0'].geometry}
            material={gltf.materials.stone}
            position={[13.91, -39.01, 53.13]}
            rotation={[Math.PI / 2, 0, -0.35]}
          />
          <T.Mesh
            geometry={gltf.nodes['Cube_(20)_stone_0'].geometry}
            material={gltf.materials.stone}
            position={[68.84, -36.93, 272.77]}
            rotation={[Math.PI / 2, 0, -0.35]}
          />
        </T.Group>
        <T.Group position={[-134.46, 25.04, 64.43]} rotation={[0, 0.1, 0]}>
          <T.Group position={[797, 0, 893]}>
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(27)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[219.76, 35.35, -116.47]}
              rotation={[Math.PI, 0.34, 0]}
              scale={[7.08, 7.22, 6.34]}
            />
            <T.Mesh
              geometry={gltf.nodes['BoostPad_(2)_BoostPadMaterial_0'].geometry}
              material={gltf.materials.BoostPadMaterial}
              position={[2.44, 16.38, -286.2]}
              rotation={[0.34, 1.22, -0.3]}
              scale={[7.36, 4.63, 8.02]}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(7)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-33.54, 15.82, -221.19]}
              rotation={[Math.PI, 0.98, 3.12]}
              scale={[5.5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(6)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-25.24, 13.88, -208.06]}
              rotation={[-Math.PI, 1.47, -Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(9)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-43.34, 11.08, -234.62]}
              rotation={[-Math.PI, 1.47, -Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(8)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-50.09, 15.11, -250.23]}
              rotation={[-Math.PI, 1.14, 3.11]}
              scale={[5.5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(10)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-57.47, 11.08, -264.99]}
              rotation={[0, 1.51, 0]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(9)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-10.5, 17.69, -202.35]}
              rotation={[-Math.PI, 0.43, 3.1]}
              scale={[5.5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(11)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[1.73, 14.26, -196.3]}
              rotation={[Math.PI, 0.92, Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(10)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-64.4, 7.37, 128.7]}
              rotation={[-3.14, -1.54, 3.12]}
              scale={[5.5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(12)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-63.5, 4.3, 113.16]}
              rotation={[Math.PI, -1.05, -Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(13)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-64.27, 4.3, 145.3]}
              rotation={[Math.PI, -1.05, -Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(12)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-65.97, 7.37, 96.67]}
              rotation={[0, -1.45, -0.03]}
              scale={[5.5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(15)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-67.44, 4.3, 81.17]}
              rotation={[Math.PI, -1.2, -Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(14)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-110.23, 10.66, -285.7]}
              rotation={[0, 1.51, 0]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(11)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-83.82, 14.19, -275.76]}
              rotation={[3.12, 0.37, 3.14]}
              scale={[9.19, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['RibBone_(5)_RibBone_0'].geometry}
              material={gltf.materials.RibBone}
              position={[-164.95, 3.89, -184.11]}
              rotation={[-1.05, -1.32, -1.04]}
              scale={3.51}
            />
            <T.Mesh
              geometry={gltf.nodes.Barracuda_barracuda_0.geometry}
              material={gltf.materials.barracuda}
              position={[-187, 8.63, -174.27]}
              rotation={[-1.64, -0.05, 0.58]}
              scale={[3.17, 3.17, 2.49]}
            />
            <T.Mesh
              geometry={gltf.nodes['RibBone_(4)_RibBone_0'].geometry}
              material={gltf.materials.RibBone}
              position={[-115.31, 4.07, -176.26]}
              rotation={[-0.67, 1.25, 0.65]}
              scale={3}
            />
            <T.Mesh
              geometry={gltf.nodes['RibBone_(3)_RibBone_0'].geometry}
              material={gltf.materials.RibBone}
              position={[42.71, 5.06, 222.91]}
              rotation={[-0.25, 0.63, 0.15]}
              scale={2.7}
            />
            <T.Mesh
              geometry={gltf.nodes['vertebra_(1)_vertebra_0'].geometry}
              material={gltf.materials.vertebra}
              position={[36.17, 7.49, 226.06]}
              rotation={[-0.43, 0.17, 0.08]}
              scale={1.5}
            />
            <T.Mesh
              geometry={gltf.nodes.vertebra_vertebra_0.geometry}
              material={gltf.materials.vertebra}
              position={[-158.24, 3.1, 136.24]}
              rotation={[-0.54, 0.77, 0.67]}
              scale={1.5}
            />
            <T.Mesh
              geometry={gltf.nodes.RibBone_RibBone_0.geometry}
              material={gltf.materials.RibBone}
              position={[-160.13, 1.38, 113.42]}
              rotation={[1.68, -1, 1.7]}
              scale={3}
            />
            <T.Mesh
              geometry={gltf.nodes['RibBone_(1)_RibBone_0'].geometry}
              material={gltf.materials.RibBone}
              position={[-162.12, 0.5, 123.57]}
              rotation={[1.83, -1.3, 1.48]}
              scale={4.01}
            />
            <T.Mesh
              geometry={gltf.nodes['RibBone_(2)_RibBone_0'].geometry}
              material={gltf.materials.RibBone}
              position={[-161.9, 1.35, 131.17]}
              rotation={[0.52, -1.49, -0.02]}
              scale={2.7}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(16)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-128.4, 9.51, -285.8]}
              rotation={[0, 1.51, 0]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(13)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-119.69, 13.09, -286.22]}
              rotation={[3.12, 0, 3.07]}
              scale={[3.13, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['pike_(17)_Pike_0'].geometry}
              material={gltf.materials.Pike}
              position={[-56, 4, 173.9]}
              rotation={[Math.PI, -1.05, -Math.PI]}
              scale={0.5}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(14)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-60.63, 7.23, 159.81]}
              rotation={[0.04, -1.29, -0.03]}
              scale={[5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(15)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-50.11, 16.67, -250.27]}
              rotation={[-Math.PI, 1.14, 3.13]}
              scale={[5.5, 4, 0.5]}
            />
            <T.Mesh
              geometry={gltf.nodes['M_wooden_rafter_(16)_M_wooden_rafter_0'].geometry}
              material={gltf.materials.M_wooden_rafter}
              position={[-83.82, 15.85, -275.8]}
              rotation={[3.12, 0.37, 3.14]}
              scale={[9.19, 4, 0.5]}
            />
          </T.Group>
          <T.Group position={[643.47, 4.6, 804.44]} rotation={[Math.PI, 0.12, Math.PI]} scale={[0.93, 0.96, 0.96]}>
            <T.Mesh
              geometry={gltf.nodes.startFrame_startFrameMaterial_0.geometry}
              material={gltf.materials.startFrameMaterial}
            />
            <T.Mesh
              geometry={gltf.nodes.startFrame_Lightboard_startFrameLightBoardMaterial_0.geometry}
              material={gltf.materials.startFrameLightBoardMaterial}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes['ArrowsignWood_(1)_ArrowsignWood_0'].geometry}
            material={gltf.materials.ArrowsignWood}
            position={[616.09, 3.2, 930.66]}
            rotation={[0, -1, 0]}
            scale={[-0.84, 0.84, 0.84]}
          />
          <T.Mesh
            geometry={gltf.nodes['ArrowsignWood_(2)_ArrowsignWood_0'].geometry}
            material={gltf.materials.ArrowsignWood}
            position={[715.2, 3.47, 977.94]}
            rotation={[Math.PI, 1.53, Math.PI]}
            scale={0.8}
          />
          <T.Mesh
            geometry={gltf.nodes['ArrowsignWood_(3)_ArrowsignWood_0'].geometry}
            material={gltf.materials.ArrowsignWood}
            position={[715.31, 3.47, 996.94]}
            rotation={[Math.PI, 1.55, Math.PI]}
            scale={0.8}
          />
          <T.Mesh
            geometry={gltf.nodes['Pier_(4)_Pier_0'].geometry}
            material={gltf.materials.Pier}
            position={[742.4, -1.62, 541.3]}
            rotation={[0, 1.25, 0]}
            scale={3.83}
          />
          <T.Mesh
            geometry={gltf.nodes['clamshell_(1)_clamshell_0'].geometry}
            material={gltf.materials.clamshell}
            position={[667.93, 5.44, 1091.1]}
            rotation={[-3.12, 0.66, 3.11]}
            scale={0.49}
          />
          <T.Mesh
            geometry={gltf.nodes['conch_(1)_conch_0'].geometry}
            material={gltf.materials.conch}
            position={[708.19, 4.72, 963.51]}
            rotation={[0, -0.79, 0.11]}
            scale={0.36}
          />
          <T.Mesh
            geometry={gltf.nodes['LavaHead_(1)_LavaHead_0'].geometry}
            material={gltf.materials.LavaHead}
            position={[931.95, 14.45, 857.64]}
            rotation={[0, 0.3, 0]}
            scale={2.5}
          />
          <T.Mesh
            geometry={gltf.nodes['primitivehut_(1)_Primitivehut_0'].geometry}
            material={gltf.materials.Primitivehut}
            position={[603.7, 4.47, 716.85]}
            rotation={[Math.PI, Math.PI / 3, Math.PI]}
            scale={4.5}
          />
          <T.Mesh
            geometry={gltf.nodes['primitivehut_(2)_Primitivehut_0'].geometry}
            material={gltf.materials.Primitivehut}
            position={[652.5, 61.7, 929.19]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={4.5}
          />
          <T.Mesh
            geometry={gltf.nodes['ArrowsignWood_(5)_ArrowsignWood_0'].geometry}
            material={gltf.materials.ArrowsignWood}
            position={[832.91, 10.08, 612.56]}
            rotation={[3.14, 0.53, -2.98]}
            scale={[-0.6, 0.6, 0.6]}
          />
          <T.Mesh
            geometry={gltf.nodes['SpiderWeb_(2)_Spiderweb_0'].geometry}
            material={gltf.materials.Spiderweb}
            position={[996.8, 25.88, 771.33]}
            rotation={[2.67, -1.35, 2.69]}
            scale={4.31}
          />
          <T.Mesh
            geometry={gltf.nodes['M_wooden_rafter_(1)_M_wooden_rafter_0'].geometry}
            material={gltf.materials.M_wooden_rafter}
            position={[830.06, 24.33, 721.19]}
            rotation={[-1.57, 0.19, -0.17]}
            scale={[2.98, 1.7, 5.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['clamshell_(2)_clamshell_0'].geometry}
            material={gltf.materials.clamshell}
            position={[759.4, 3.4, 1099.71]}
            rotation={[3.12, 0.66, 3.14]}
            scale={0.49}
          />
          <T.Mesh
            geometry={gltf.nodes['Pier_(5)_Pier_0'].geometry}
            material={gltf.materials.Pier}
            position={[860.1, -1.6, 1324.5]}
            rotation={[0, -1.12, 0]}
            scale={3.8}
          />
          <T.Mesh
            geometry={gltf.nodes['Pier_(2)_Pier_0'].geometry}
            material={gltf.materials.Pier}
            position={[616.4, -1.6, 1096.9]}
            rotation={[0, -1.12, 0]}
            scale={3.8}
          />
          <T.Mesh
            geometry={gltf.nodes['fishing_boat_(3)_fishing_boat_0'].geometry}
            material={gltf.materials.fishing_boat}
            position={[596.5, 0.26, 1101.8]}
            rotation={[0, 0.26, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['Seagull_(2)_seagull_0'].geometry}
            material={gltf.materials.seagull}
            position={[1012.96, 23.77, 696.47]}
            rotation={[0, 1.38, 0]}
            scale={0.28}
          />
          <T.Mesh
            geometry={gltf.nodes.M_wooden_rafter_M_wooden_rafter_0.geometry}
            material={gltf.materials.M_wooden_rafter}
            position={[830.06, 28.22, 721.19]}
            rotation={[-1.57, 0, -0.17]}
            scale={[2.98, 1.7, 5.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['SpiderWeb_(1)_Spiderweb_0'].geometry}
            material={gltf.materials.Spiderweb}
            position={[871.17, 30.45, 874.7]}
            rotation={[2.67, 1.37, -2.73]}
            scale={4.31}
          />
          <T.Mesh
            geometry={gltf.nodes.SpiderWeb_Spiderweb_0.geometry}
            material={gltf.materials.Spiderweb}
            position={[1027.12, 30.48, 785.35]}
            rotation={[-0.47, 1.35, 0.45]}
            scale={4.31}
          />
          <T.Mesh
            geometry={gltf.nodes['ArrowsignWood_(4)_ArrowsignWood_0'].geometry}
            material={gltf.materials.ArrowsignWood}
            position={[820.5, 12.7, 605.6]}
            rotation={[-3.13, 0.46, -2.97]}
            scale={[-0.6, 0.6, 0.6]}
          />
          <T.Mesh
            geometry={gltf.nodes['sharkjawbone_(1)_Sharkjawbone_0'].geometry}
            material={gltf.materials.Sharkjawbone}
            position={[640.03, 5.08, 980.71]}
            rotation={[-2.39, 0.61, 2.64]}
            scale={[2.01, 2.21, 2.01]}
          />
          <T.Mesh
            geometry={gltf.nodes.sharkjawbone_Sharkjawbone_0.geometry}
            material={gltf.materials.Sharkjawbone}
            position={[612.35, 10.19, 750.96]}
            rotation={[1.57, 0.97, -1.57]}
            scale={[1, 1.1, 1]}
          />
          <T.Mesh
            geometry={gltf.nodes.CobbestoneRoadTransition2_beach_stones_0.geometry}
            material={gltf.materials.beach_stones}
            position={[835.17, 11.09, 606.51]}
            rotation={[-0.04, -0.52, -0.16]}
            scale={[1, 0.54, 1]}
          />
          <T.Mesh
            geometry={gltf.nodes['CobbestoneRoadTransition_(1)_beach_stones_0'].geometry}
            material={gltf.materials.beach_stones}
            position={[654.57, 5.05, 708.83]}
            rotation={[0, 0.05, 0]}
            scale={[-1, 0.38, 1]}
          />
          <T.Mesh
            geometry={gltf.nodes.CobbestoneRoadTransition_beach_stones_0.geometry}
            material={gltf.materials.beach_stones}
            position={[831.9, 6.84, 1064.22]}
            rotation={[0, -0.22, 0.02]}
            scale={[0.9, 0.4, 0.9]}
          />
          <T.Mesh
            geometry={gltf.nodes['IslandBillboard_(1)_island_0'].geometry}
            material={gltf.materials.island}
            position={[654.8, 35.9, 1320.6]}
            rotation={[0, -0.34, 0]}
            scale={80}
          />
          <T.Mesh
            geometry={gltf.nodes.IslandBillboard_island_0.geometry}
            material={gltf.materials.island}
            position={[655.2, 31.2, 371.8]}
            rotation={[0, 0.67, 0]}
            scale={68.47}
          />
          <T.Mesh
            geometry={gltf.nodes.Island2Billboard_island2_0.geometry}
            material={gltf.materials.island2}
            position={[387.8, 21.5, 1174]}
            rotation={[0, -0.81, 0]}
            scale={[158.05, 52.68, 52.68]}
          />
          <T.Mesh
            geometry={gltf.nodes['primitivehut_(4)_Primitivehut_0'].geometry}
            material={gltf.materials.Primitivehut}
            position={[831.66, 3.94, 580.57]}
            rotation={[0, -0.52, 0]}
            scale={4.5}
          />
          <T.Mesh
            geometry={gltf.nodes['primitivehut_(3)_Primitivehut_0'].geometry}
            material={gltf.materials.Primitivehut}
            position={[720.5, 4.51, 961.35]}
            rotation={[0, -1.31, 0]}
            scale={4.5}
          />
          <T.Mesh
            geometry={gltf.nodes['primitivehut_(5)_Primitivehut_0'].geometry}
            material={gltf.materials.Primitivehut}
            position={[656, 28.27, 537.1]}
            scale={4.5}
          />
          <T.Mesh
            geometry={gltf.nodes.primitivehut_Primitivehut_0.geometry}
            material={gltf.materials.Primitivehut}
            position={[607.06, 4.47, 755.36]}
            rotation={[0, Math.PI / 2, 0]}
            scale={4.5}
          />
          <T.Mesh
            geometry={gltf.nodes.LavaHead_LavaHead_0.geometry}
            material={gltf.materials.LavaHead}
            position={[892.15, 14.45, 950.61]}
            rotation={[-Math.PI, -Math.PI / 4, Math.PI]}
            scale={2.5}
          />
          <T.Mesh
            geometry={gltf.nodes['conch_(2)_conch_0'].geometry}
            material={gltf.materials.conch}
            position={[850.1, 8.91, 629.54]}
            scale={0.55}
          />
          <T.Mesh
            geometry={gltf.nodes.clamshell_clamshell_0.geometry}
            material={gltf.materials.clamshell}
            position={[652.84, 4.39, 1030.9]}
            rotation={[0.15, -0.91, 0.19]}
            scale={0.4}
          />
          <T.Mesh
            geometry={gltf.nodes['Seagull_(1)_seagull_0'].geometry}
            material={gltf.materials.seagull}
            position={[715.02, 32.37, 1151.99]}
            rotation={[0, 1.46, 0]}
            scale={0.4}
          />
          <T.Mesh
            geometry={gltf.nodes.Seagull_seagull_0.geometry}
            material={gltf.materials.seagull}
            position={[620.06, 16.02, 802.01]}
            rotation={[0, 1.06, 0]}
            scale={0.38}
          />
          <T.Mesh
            geometry={gltf.nodes['Pier_(3)_Pier_0'].geometry}
            material={gltf.materials.Pier}
            position={[826.9, -1.62, 587.7]}
            rotation={[Math.PI, Math.PI / 6, Math.PI]}
            scale={3.83}
          />
          <T.Mesh
            geometry={gltf.nodes.ArrowsignWood_ArrowsignWood_0.geometry}
            material={gltf.materials.ArrowsignWood}
            position={[628.12, 3.2, 945.55]}
            rotation={[0, -0.81, 0]}
            scale={[-0.84, 0.84, 0.84]}
          />
          <T.Mesh
            geometry={gltf.nodes.Pier_Pier_0.geometry}
            material={gltf.materials.Pier}
            position={[555.8, -1.71, 848.8]}
            rotation={[-Math.PI, -1.31, Math.PI]}
            scale={3.9}
          />
          <T.Mesh
            geometry={gltf.nodes['fishing_boat_(2)_fishing_boat_0'].geometry}
            material={gltf.materials.fishing_boat}
            position={[763.7, 0.27, 517.2]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes.fishing_boat_fishing_boat_0.geometry}
            material={gltf.materials.fishing_boat}
            position={[509.08, 0.26, 906.2]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes.brazier_brazier_mat_0.geometry}
            material={gltf.materials.brazier_mat}
            position={[820.18, 22.28, 944.5]}
            rotation={[0, 1.31, 0]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(6)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[1053.08, 95.08, 528.96]}
            rotation={[0, -0.17, 0]}
            scale={4}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(5)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[1086.17, 12.78, 664.53]}
            rotation={[0, 0.13, -0.23]}
            scale={4}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(3)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[916.13, 14.41, 921.7]}
            rotation={[0, -0.13, 0]}
            scale={[3.49, 3.61, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(2)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[864.26, 11.23, 961.98]}
            rotation={[0, -0.09, 0]}
            scale={[4, 4.19, 4]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(4)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[919.23, 14.41, 866.1]}
            rotation={[0, 0.13, 0]}
            scale={[3.49, 3.61, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(8)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[1166.38, 94.5, 589.73]}
            rotation={[0, -1.06, 0]}
            scale={4}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(9)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[1174.2, 94.72, 672.9]}
            rotation={[-Math.PI, -1.48, Math.PI]}
            scale={4}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(10)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[877.54, 12.52, 872.34]}
            rotation={[0, 0.31, 0]}
            scale={[3.49, 4.26, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(11)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[840.53, 11.55, 889.53]}
            rotation={[0, 0.87, 0]}
            scale={[3.49, 4.46, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(12)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[816.56, 9.94, 943.87]}
            rotation={[0, 1.44, 0]}
            scale={[3.49, 4.79, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['brazier_(1)_brazier_mat_0'].geometry}
            material={gltf.materials.brazier_mat}
            position={[843.33, 22.28, 892.01]}
            rotation={[0, Math.PI / 4, 0]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['brazier_(2)_brazier_mat_0'].geometry}
            material={gltf.materials.brazier_mat}
            position={[878.62, 22.28, 875.96]}
            rotation={[0, 0.26, 0]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['fishing_boat_(1)_fishing_boat_0'].geometry}
            material={gltf.materials.fishing_boat}
            position={[769.1, 0.26, 1305.6]}
            rotation={[Math.PI, 1.31, Math.PI]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pier_(1)_Pier_0'].geometry}
            material={gltf.materials.Pier}
            position={[602.1, -1.6, 1045.9]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={3.8}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(13)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[990.22, 12.22, 773.81]}
            rotation={[0, 1.19, 0]}
            scale={[3.49, 3.98, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['brazier_(3)_brazier_mat_0'].geometry}
            material={gltf.materials.brazier_mat}
            position={[993.7, 21.34, 775.28]}
            rotation={[0, 1.14, 0]}
            scale={[1.5, 1.4, 1.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(14)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[960.87, 13.01, 835.49]}
            rotation={[0, 0.92, -0.03]}
            scale={[3.49, 4.13, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['brazier_(4)_brazier_mat_0'].geometry}
            material={gltf.materials.brazier_mat}
            position={[964.01, 22.47, 837.62]}
            rotation={[0, 0.88, -0.03]}
            scale={[1.5, 1.45, 1.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(15)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[1033.08, 13.16, 787.87]}
            rotation={[0, 1.19, 0]}
            scale={[3.49, 4.14, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['Pillar_(16)_Pillar_0'].geometry}
            material={gltf.materials.Pillar}
            position={[1019.96, 12.95, 835.21]}
            rotation={[-0.06, -1.17, -0.04]}
            scale={[3.49, 4.18, 3.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['brazier_(5)_brazier_mat_0'].geometry}
            material={gltf.materials.brazier_mat}
            position={[1016.66, 22.62, 836.43]}
            rotation={[-0.07, -1.21, -0.05]}
            scale={[1.5, 1.47, 1.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(9)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[677.46, 10.3, 622.87]}
            rotation={[-0.15, 0, 0]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(8)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[820.87, 15.31, 635.94]}
            rotation={[0.06, 0, -0.18]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(7)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[1008.9, 14.95, 712.61]}
            rotation={[0.28, 0.37, -0.11]}
            scale={1.3}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(6)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[1050.33, 18.36, 602.06]}
            rotation={[0.17, -0.6, 0.03]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(5)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[803.09, 7.12, 1021.62]}
            rotation={[0.29, 0.02, 0.19]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(4)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[739.62, 4.32, 1068.49]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(3)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[700.33, 6.73, 1143.8]}
            rotation={[-0.23, 0.28, -0.07]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(2)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[723.77, 4.56, 1051.91]}
            rotation={[0, -1, 0.2]}
          />
          <T.Mesh
            geometry={gltf.nodes['BigFlower_(1)_flower_0'].geometry}
            material={gltf.materials.flower}
            position={[699.78, 4.72, 926.67]}
            rotation={[0, -0.53, 0.27]}
            scale={1.2}
          />
          <T.Mesh
            geometry={gltf.nodes.BigFlower_flower_0.geometry}
            material={gltf.materials.flower}
            position={[593.74, 27.23, 920.12]}
            rotation={[-1.44, 0.01, -0.8]}
            scale={1.42}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(2)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[604.98, 2.93, 926.26]}
            rotation={[-3.14, -0.03, -2.73]}
            scale={1.47}
          />
          <T.Mesh
            geometry={gltf.nodes.palmtreesmall_palmtree_0.geometry}
            material={gltf.materials.palmtree}
            position={[590.79, 1.98, 784.38]}
            rotation={[-2.87, 0.93, -Math.PI]}
            scale={1.46}
          />
          <T.Mesh
            geometry={gltf.nodes.palmtree_palmtree_0.geometry}
            material={gltf.materials.palmtree}
            position={[587.4, 2.7, 778.7]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(3)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[622.12, 61.31, 924.23]}
            rotation={[0, 0, 0.42]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(4)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[789.45, 3.82, 1020.15]}
            rotation={[2.75, -1.12, 2.27]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(5)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[880.9, 38.6, 1050.3]}
            rotation={[2.97, -0.03, 2.87]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(6)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[885.23, 52.1, 1106.97]}
            rotation={[3.12, -1.34, 2.89]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(7)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[871.33, 37.76, 1181.22]}
            rotation={[2.52, -0.96, 1.99]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(8)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[645.85, 2.8, 1090.17]}
            rotation={[Math.PI, -0.26, -2.72]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(9)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[771.3, 5.58, 1161.68]}
            rotation={[Math.PI, -0.26, -2.72]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(10)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[728.9, 4, 1021.45]}
            rotation={[-3.09, 0.93, 2.6]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(1)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[861.7, 82.3, 1353.7]}
            rotation={[0, -1.29, Math.PI / 2]}
            scale={[-0.62, 0.82, 1.12]}
          />
          <T.Mesh
            geometry={gltf.nodes.palm_billboard_palm_billboard_0.geometry}
            material={gltf.materials.palm_billboard}
            position={[869.34, 86.4, 1348.75]}
            rotation={[Math.PI, Math.PI / 3, Math.PI / 2]}
            scale={[0.95, 1.25, 1.63]}
          />
          <T.Mesh
            geometry={gltf.nodes.palmtreesmall001_palmtree_0.geometry}
            material={gltf.materials.palmtree}
            position={[600.4, 28, 565.3]}
            rotation={[-2.16, -1.29, -2.45]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes.palmtree001_palmtree_0.geometry}
            material={gltf.materials.palmtree}
            position={[607.02, 28.1, 555.46]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(1)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[671.7, 28, 519.9]}
            rotation={[0.16, -0.41, -0.37]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(2)001_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[568.9, 37.9, 618.8]}
            rotation={[-0.23, 0.1, -0.25]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(1)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[568.9, 38.8, 625.2]}
            rotation={[Math.PI, 1.31, Math.PI]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(2)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[876.9, 44.5, 737.5]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(3)001_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[886.15, 43.01, 736.56]}
            rotation={[-0.12, 0.41, -0.51]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(4)001_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[754.03, 40.3, 705]}
            rotation={[0.16, 1.03, -0.61]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(3)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[628.95, 60.97, 930.8]}
            rotation={[2.49, 1.24, -2.47]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(4)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[793.99, 4.08, 1018]}
            rotation={[-2.53, 1.16, 2.86]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(5)001_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[730.38, 5.7, 664.01]}
            rotation={[0.16, 1.03, -0.61]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(5)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[688.3, 6.4, 628.02]}
            rotation={[0, 1.57, 0]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(6)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[719, 6.87, 650.2]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(6)001_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[701.46, 5.07, 667.67]}
            rotation={[2.98, -1.03, 2.53]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(2)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[877.96, 43.9, 1065.29]}
            rotation={[-0.27, 0.12, 1.68]}
            scale={[-0.89, 1.18, 1.67]}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(7)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[1017.4, 47.33, 547.64]}
            rotation={[0.5, 0, 0.36]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(7)001_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[995.8, 29.4, 564.66]}
            rotation={[-2.97, -0.08, 3.12]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(3)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[1114.1, 129.3, 517]}
            rotation={[-0.79, 1.21, -0.82]}
            scale={[0.95, 1.25, 1.63]}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(4)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[1069.5, 58.6, 567.4]}
            rotation={[0, 1.27, -Math.PI / 2]}
            scale={[0.95, 1.25, 1.63]}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(5)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[1118.6, 58.6, 603.6]}
            rotation={[-Math.PI, -0.75, Math.PI / 2]}
            scale={[0.95, 1.25, 1.63]}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(8)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[1107.77, 29.5, 615.73]}
            rotation={[2.82, -0.45, 2.73]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(9)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[642.74, 2.5, 1089.94]}
            rotation={[0.26, -0.76, 0.24]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(10)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[728.58, 3.56, 1026.45]}
            rotation={[-0.07, -0.2, 0.4]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(6)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[878.5, 50.72, 1080.1]}
            rotation={[Math.PI, -0.01, Math.PI / 2]}
            scale={[0.95, 1.25, 1.63]}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(7)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[865.9, 45.9, 1108.66]}
            rotation={[0.45, -0.47, 1.7]}
            scale={[-0.76, 1.01, 1.21]}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(11)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[870.2, 37.05, 524.46]}
            rotation={[0.31, -0.25, -0.13]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(12)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[675.3, 8.2, 625.1]}
            rotation={[0, -Math.PI / 6, 0.44]}
            scale={1.29}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(8)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[1138.2, 127.8, 531.5]}
            rotation={[-2.57, -0.87, -0.99]}
            scale={[-0.95, 1.25, 1.63]}
          />
          <T.Mesh
            geometry={gltf.nodes['palm_billboard_(9)_palm_billboard_0'].geometry}
            material={gltf.materials.palm_billboard}
            position={[1125.8, 128.9, 521.4]}
            rotation={[0.17, 1.03, -1.65]}
            scale={[1.27, 1.67, 2.18]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(5)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[684.92, 5.02, 727.49]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(4)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[867.76, 14.47, 655.11]}
            rotation={[-2.27, -1.29, -2.64]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(3)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[695.58, 14.89, 561.57]}
            rotation={[0.31, -0.46, -0.18]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(2)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1058.25, 15.61, 623.99]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(1)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1084.12, 15.36, 687.02]}
          />
          <T.Mesh
            geometry={gltf.nodes.Shrub_PlantMaterial_0.geometry}
            material={gltf.materials.PlantMaterial}
            position={[812.64, 8.25, 1021.52]}
            rotation={[0.35, -0.07, 0.23]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(6)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[797.48, 14.44, 691.58]}
            rotation={[0.08, 0.12, -0.35]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(7)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[824.46, 14.65, 644.81]}
            rotation={[0.56, -1.09, 0.23]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(8)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[865.86, 24.84, 1034.37]}
            rotation={[0.1, -0.07, 0.23]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(9)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[861.49, 24.84, 1085.43]}
            rotation={[1.52, -1.47, 1.74]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(10)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[730.14, 12.56, 621.93]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(11)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[685.74, 11.11, 611.36]}
            rotation={[0, 1.05, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(12)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[697.07, 12.12, 610.36]}
            rotation={[0.71, 0.9, -0.48]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(13)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[850.11, 5.76, 1086.69]}
            rotation={[0.06, -1, 0.27]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(27)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[945.03, 14.15, 687.47]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(26)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[844.46, 17.07, 721.33]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(25)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[993.4, 14.23, 753.75]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(24)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[872.14, 38.95, 527.77]}
            rotation={[0, 0.46, 0]}
            scale={2.04}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(17)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[728.54, 6, 1156.37]}
            rotation={[0, 0.83, -0.2]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(16)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[739.51, 6.3, 1158.36]}
            rotation={[0, -1.24, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(15)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[749.57, 6.3, 1160.41]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(14)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[643.8, 3.2, 1084.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(12)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[700.11, 3.76, 931.19]}
            rotation={[0, 0, 0.47]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(6)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1094.01, 30.11, 725.01]}
            rotation={[-2.41, 1.21, 2.42]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(3)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[682.22, 27.8, 544.61]}
          />
          <T.Mesh
            geometry={gltf.nodes.Shrub001_PlantMaterial_0.geometry}
            material={gltf.materials.PlantMaterial}
            position={[1022.61, 13.4, 670.5]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(1)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1015.32, 13.04, 657.02]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(2)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1000.45, 12.87, 648.19]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(5)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[606.9, 28.3, 562.6]}
            rotation={[0, -0.68, 0]}
            scale={1.27}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(4)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[674.88, 28.02, 544.02]}
            rotation={[0, -Math.PI / 3, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(7)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1112.27, 29.23, 653.44]}
            rotation={[-2.9, 0.28, 3.04]}
            scale={[1.19, 1.56, 1.19]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(8)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1100.66, 29.39, 617.92]}
            rotation={[-2.26, 1.26, 2.25]}
            scale={[1.19, 1.56, 1.19]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(9)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1084.31, 15.34, 671.77]}
            rotation={[-2.26, 1.26, 2.25]}
            scale={[1.19, 1.56, 1.19]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(10)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1096.56, 96.59, 536.22]}
            rotation={[-2.84, 0.66, 2.93]}
            scale={[1.19, 1.56, 1.19]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(11)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1128.15, 96.17, 554.03]}
            rotation={[-2.9, -0.19, -3.12]}
            scale={[1.19, 1.56, 1.19]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(13)001_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[672.31, 3.94, 900.8]}
            rotation={[0, 0.63, 0.15]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(18)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[582.68, 30.11, 920.35]}
            rotation={[-1.21, -0.64, -0.31]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(19)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[598.5, 28.83, 926.13]}
            rotation={[-1.83, -0.46, -0.77]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(20)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[677.36, 30.62, 1119.37]}
            rotation={[0.19, -0.37, 0.13]}
            scale={1.17}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(21)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[763.77, 32, 1163.34]}
            rotation={[0.19, -0.37, 0.13]}
            scale={1.17}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(22)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[721.63, 4.36, 1006.08]}
            rotation={[0, 0, 0.47]}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(23)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[723.57, 3.93, 1056.14]}
            rotation={[0, -0.26, 0.47]}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(8)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[1066.89, 16.1, 633.13]}
            rotation={[0, 0.19, 0]}
            scale={1.42}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(7)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[1001.22, 13.82, 731.62]}
            rotation={[0, -1.54, 0]}
            scale={1.56}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(6)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[841.35, 9.53, 647.76]}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(5)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[886.6, 15.7, 719]}
            rotation={[-0.19, 0, 0]}
            scale={1.82}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(4)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[1012.65, 13.59, 707.61]}
            scale={1.57}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(3)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[809.34, 6.86, 1022.58]}
            rotation={[-0.11, 0.64, 0.18]}
            scale={1.74}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(1)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[720.02, 3.69, 1020.57]}
            rotation={[-0.05, 0.49, 0.07]}
            scale={1.67}
          />
          <T.Mesh
            geometry={gltf.nodes.Fern_fern_mat_0.geometry}
            material={gltf.materials.fern_mat}
            position={[688.94, 9.59, 618.43]}
            rotation={[0, -1.22, 0]}
            scale={2}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(2)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[744.56, 3.23, 1071.1]}
            rotation={[-0.02, 0.03, 0.06]}
            scale={1.67}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(20)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[763, 6.4, 1013.55]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(11)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[916.49, 42.55, 735.57]}
            rotation={[Math.PI / 2, -0.22, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(10)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[696.24, 49.06, 820.36]}
            rotation={[Math.PI / 2, -0.06, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(6)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[559.47, 41.1, 639.34]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(5)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[588.54, 30.47, 570.32]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes.Bush_BushMaterial_0.geometry}
            material={gltf.materials.BushMaterial}
            position={[725.06, 6.9, 683.95]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.06}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(1)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[711, 7.96, 676.69]}
            rotation={[Math.PI / 2, 0, 2.88]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(2)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[719.68, 9.8, 670.76]}
            rotation={[Math.PI / 2, 0, 2.88]}
            scale={0.06}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(3)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[702, 8.56, 658.7]}
            rotation={[Math.PI / 2, 0, 2.88]}
            scale={0.04}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(4)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[709.3, 9.1, 654.1]}
            rotation={[Math.PI / 2, 0, 2.88]}
            scale={0.06}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(7)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[576.26, 32.54, 574.65]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.08}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(8)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[588.2, 30.47, 548.4]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(9)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[550.85, 43.3, 632.08]}
            rotation={[Math.PI / 2, 0, 2.81]}
            scale={0.07}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(12)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[925.99, 43.5, 747.43]}
            rotation={[1.7, 0.18, -2.54]}
            scale={0.08}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(13)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[900.42, 42.88, 742.72]}
            rotation={[1.78, -0.09, 2.43]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(14)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[581.9, 30.3, 685.3]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(15)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[691.42, 45.69, 765.44]}
            rotation={[Math.PI / 2, -0.13, -3.1]}
            scale={0.03}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(16)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[700.4, 46.5, 764.7]}
            rotation={[Math.PI / 2, -0.13, -3.1]}
            scale={0.06}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(17)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[701.8, 43.95, 723.62]}
            rotation={[1.7, -0.08, 2.26]}
            scale={0.05}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(18)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[687.99, 49.99, 825.28]}
            rotation={[1.5, -0.08, 2.26]}
            scale={0.04}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(19)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[610.19, 63.66, 925.9]}
            rotation={[1.47, -0.06, 1.96]}
            scale={0.04}
          />
          <T.Mesh
            geometry={gltf.nodes['Bush_(21)_BushMaterial_0'].geometry}
            material={gltf.materials.BushMaterial}
            position={[749.71, 6.34, 1007.45]}
            rotation={[Math.PI / 2, 0, 1.25]}
            scale={0.08}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(13)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[1092.28, 14.25, 654.39]}
            rotation={[2.86, -0.35, 2.54]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(14)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[1050.9, 27.5, 575.3]}
            rotation={[-3, -1.47, 2.88]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(11)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[1040.2, 17.4, 590.1]}
            rotation={[-2.98, -0.69, 2.86]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(15)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[1050, 16.8, 593.7]}
            rotation={[0.42, -0.53, 0.03]}
            scale={1.68}
          />
          <T.Mesh
            geometry={gltf.nodes['Fern_(9)_fern_mat_0'].geometry}
            material={gltf.materials.fern_mat}
            position={[1045.5, 18.2, 597.5]}
            rotation={[0, -0.84, 0]}
            scale={1.42}
          />
          <T.Mesh
            geometry={gltf.nodes['Shrub_(28)_PlantMaterial_0'].geometry}
            material={gltf.materials.PlantMaterial}
            position={[1038.97, 18.17, 595.64]}
            rotation={[0.27, -0.9, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(12)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[755.94, 5.29, 1171.25]}
            rotation={[0.52, -1.19, 0.25]}
            scale={1.33}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(16)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[728.58, 3.6, 973.1]}
            rotation={[-0.08, 0.4, 0.44]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(17)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[608.3, 3.6, 951.9]}
            rotation={[-3.12, -0.72, -2.82]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(13)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[931.9, 15.7, 620.9]}
            rotation={[-3.11, -0.43, 2.85]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(14)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[947.9, 15.7, 601.6]}
            rotation={[-2.76, 0.76, 2.96]}
            scale={1.54}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtreesmall_(15)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[590.79, 1.98, 887.58]}
            rotation={[-2.97, 0.33, -2.98]}
            scale={1.46}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(18)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[587.4, 2.7, 881.9]}
            rotation={[0, 0.61, 0]}
            scale={1.5}
          />
          <T.Mesh
            geometry={gltf.nodes['palmtree_(19)_palmtree_0'].geometry}
            material={gltf.materials.palmtree}
            position={[835.3, 2.5, 1166.5]}
            rotation={[-2.8, 0.32, 2.69]}
            scale={1.4}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(6)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[1091.57, 11.7, 684.21]}
            rotation={[-0.36, -0.55, 0.34]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(3)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[583.14, 27.7, 657.9]}
            rotation={[0, -1.57, 0]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(2)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[1066.42, 15.7, 624.85]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes.moaistatue_MoaiStatue_0.geometry}
            material={gltf.materials.MoaiStatue}
            position={[815.14, 5.43, 1141.43]}
            rotation={[-Math.PI, -0.26, Math.PI]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(1)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[715.51, 5.75, 1152.9]}
            rotation={[Math.PI, 0.26, Math.PI]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(4)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[678.9, 5.07, 1118.6]}
            rotation={[Math.PI, Math.PI / 6, Math.PI]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(5)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[764.5, 6.13, 1162]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(7)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[634.4, 27.9, 541.5]}
            rotation={[0, 0.26, 0]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['moaistatue_(8)_MoaiStatue_0'].geometry}
            material={gltf.materials.MoaiStatue}
            position={[583.56, 33.81, 574.34]}
            rotation={[2.04, 1.29, -0.34]}
            scale={2.2}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L02_(3)_Rock_gray_0'].geometry}
            material={gltf.materials.Rock_gray}
            position={[876.03, 14, 652.82]}
            rotation={[0, 0.07, 0]}
            scale={16.3}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L02_(5)_Rock_gray_0'].geometry}
            material={gltf.materials.Rock_gray}
            position={[811.68, 14, 632.13]}
            rotation={[0, -0.45, 0]}
            scale={16.3}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_M02_(4)_Rock_gray2_0'].geometry}
            material={gltf.materials.Rock_gray2}
            position={[806.13, 15, 628.49]}
            rotation={[-Math.PI, -1.52, Math.PI]}
            scale={27.61}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_M01_(3)_cliff_0'].geometry}
            material={gltf.materials.cliff}
            position={[674.38, 11.8, 822.83]}
            rotation={[-0.07, 0.05, 1.57]}
            scale={[24.75, 37.38, 43.58]}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L01_(6)_cliff_0'].geometry}
            material={gltf.materials.cliff}
            position={[674.7, 21.3, 846.4]}
            rotation={[1.6, -0.2, 1.6]}
            scale={18.84}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_M01_(2)_Rock_brown2_0'].geometry}
            material={gltf.materials.Rock_brown2}
            position={[919.31, 14.53, 930.41]}
            rotation={[-0.16, 1.22, 0.15]}
            scale={[21.41, 27.9, 21.41]}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L01_(5)_Rock_brown1_0'].geometry}
            material={gltf.materials.Rock_brown1}
            position={[872.27, 11.88, 968.23]}
            rotation={[2.87, -0.63, 2.87]}
            scale={[9.79, 14.25, 9.79]}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_M01_(1)_Rock_brown2_0'].geometry}
            material={gltf.materials.Rock_brown2}
            position={[862.01, 10.94, 976.98]}
            rotation={[-2.99, 1.14, 3]}
            scale={20.21}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L01_(4)_Rock_brown1_0'].geometry}
            material={gltf.materials.Rock_brown1}
            position={[680.61, 7.3, 634.81]}
            rotation={[0, 0.35, 0]}
            scale={16.17}
          />
          <T.Mesh
            geometry={gltf.nodes.rock_L02_Rock_gray_0.geometry}
            material={gltf.materials.Rock_gray}
            position={[708.61, 3.56, 939.8]}
            rotation={[Math.PI, Math.PI / 4, Math.PI]}
            scale={[14.04, 27.15, 14.04]}
          />
          <T.Mesh
            geometry={gltf.nodes.rock_M02_Rock_gray2_0.geometry}
            material={gltf.materials.Rock_gray2}
            position={[670.91, 4.53, 831.88]}
            rotation={[-Math.PI, -0.36, Math.PI]}
            scale={34.4}
          />
          <T.Mesh
            geometry={gltf.nodes.rock_L01_Rock_brown1_0.geometry}
            material={gltf.materials.Rock_brown1}
            position={[668.25, 4.4, 861.87]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={11.47}
          />
          <T.Mesh
            geometry={gltf.nodes.rock_M01_Rock_brown2_0.geometry}
            material={gltf.materials.Rock_brown2}
            position={[669.94, 4.5, 846.25]}
            rotation={[Math.PI, 0.21, Math.PI]}
            scale={35.37}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L01_(1)_Rock_brown1_0'].geometry}
            material={gltf.materials.Rock_brown1}
            position={[1016.63, 14.97, 850.22]}
            rotation={[-Math.PI, -Math.PI / 4, Math.PI]}
            scale={11.47}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L01_(2)_Rock_brown1_0'].geometry}
            material={gltf.materials.Rock_brown1}
            position={[1024.24, 12.72, 842.47]}
            rotation={[-Math.PI, Math.PI / 4, -2.87]}
            scale={[11.47, 29.6, 11.47]}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_L01_(3)_Rock_brown1_0'].geometry}
            material={gltf.materials.Rock_brown1}
            position={[711.96, 3.97, 946.82]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={11.47}
          />
          <T.Mesh
            geometry={gltf.nodes['rock_M01_(4)_cliff_0'].geometry}
            material={gltf.materials.cliff}
            position={[678.02, 8.84, 768.84]}
            rotation={[2.99, -0.03, 1.57]}
            scale={[24.75, 37.38, 32.4]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(25)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[859.47, 18.56, 1011.2]}
            rotation={[0, 0, 1.57]}
            scale={[1.37, 1.61, 1.61]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(23)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[813.48, 25.3, 1004.31]}
            rotation={[3.01, 0.94, -1.77]}
            scale={[2.34, 2.34, 2.62]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(22)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[895.57, 53.6, 1082.28]}
            rotation={[Math.PI, -0.08, 1.71]}
            scale={[1.52, 1.65, 1.65]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(20)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[842.01, 5.67, 1127.71]}
            rotation={[-3.02, -0.08, 1.66]}
            scale={[1.45, 1.77, 1.77]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(19)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[556.13, 2.54, 923.43]}
            rotation={[0, 1.44, -1.57]}
            scale={[1.58, 1.87, 1.87]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(18)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[613.71, 17.69, 560.88]}
            rotation={[0.12, -0.75, -1.52]}
            scale={[1.91, 1.92, 1.92]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(17)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[865.62, 45.52, 746.9]}
            rotation={[0, 1.21, -1.58]}
            scale={[3.58, 2.98, 2.98]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(16)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[1001.57, 33.39, 551.65]}
            rotation={[2.95, -0.38, 1.67]}
            scale={[2.76, 2.3, 2.3]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(15)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[1040.96, 34.45, 772.48]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[2.02, 2.15, 2.15]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(13)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[986.62, 29.03, 764.34]}
            rotation={[0.21, -0.06, -1.83]}
            scale={[1.63, 2.03, 2.03]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(12)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[1023.42, 35.62, 766.37]}
            rotation={[-1.57, -1.47, 0]}
            scale={[1.2, 1.25, 1.25]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(11)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[987.39, 16.36, 574.61]}
            rotation={[3.03, -0.73, 1.74]}
            scale={[1.79, 1.89, 1.89]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(10)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[914.59, 17.08, 722.26]}
            rotation={[0.72, 1.46, -2.08]}
            scale={[2.13, 2.75, 2.75]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(9)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[842.18, 1.95, 619.93]}
            rotation={[0, 0.6, -1.28]}
            scale={[1.5, 1.67, 1.68]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(8)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[878.03, 1.35, 644.29]}
            rotation={[0.35, 1.33, -1.79]}
            scale={[2.17, 2.67, 2.67]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(7)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[861.75, 1.83, 640.55]}
            rotation={[0.48, 0.68, -1.68]}
            scale={[1.72, 1.43, 1.43]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(5)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[863.64, 15.35, 723.57]}
            rotation={[-0.25, 0.43, 0.11]}
            scale={[2.03, 1.69, 1.69]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(4)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[694.35, -0.26, 537.88]}
            rotation={[0.34, 0.56, -1.22]}
            scale={[3.13, 2.61, 2.61]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(3)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[688.51, 12.56, 548.87]}
            rotation={[0.52, 0.21, -1.03]}
            scale={[1.98, 1.65, 1.65]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(2)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[572.94, 28.88, 648.62]}
            rotation={[-0.25, 0.34, -0.97]}
            scale={[2.34, 1.95, 1.95]}
          />
          <T.Mesh
            geometry={gltf.nodes.beachrock_beachrock_0.geometry}
            material={gltf.materials.beachrock}
            position={[705.8, 6.7, 703.2]}
            rotation={[3.07, 1.15, 1.89]}
            scale={[2.77, 2.31, 2.31]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(1)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[745.56, 10.33, 698.21]}
            rotation={[3.07, 1.15, 1.89]}
            scale={[3.48, 3.07, 3.07]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(14)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[989.52, 32.17, 764.67]}
            rotation={[2.85, -1.05, -2.07]}
            scale={[1.45, 2.03, 2.03]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(21)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[844.79, 7.34, 1138.54]}
            rotation={[-3.02, -0.08, 1.66]}
            scale={[3, 2.7, 2.7]}
          />
          <T.Mesh
            geometry={gltf.nodes['beachrock_(24)_beachrock_0'].geometry}
            material={gltf.materials.beachrock}
            position={[858.2, 31.75, 1010.55]}
            rotation={[-0.43, 0.83, 1.97]}
            scale={[2.34, 2.34, 2.62]}
          />
        </T.Group>
        <T.Mesh
          geometry={gltf.nodes.StartLine_FinishLine_0.geometry}
          material={gltf.materials.FinishLine}
          position={[583, 43.22, 803.95]}
          rotation={[Math.PI / 2, 0, 0.03]}
        />
        <T.Group position={[2465.02, 25.04, -188.92]} rotation={[0, 0.1, 0]} scale={10}>
          <T.Mesh geometry={gltf.nodes.island_basemodel_cliff_0.geometry} material={gltf.materials.cliff} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_grass_0.geometry} material={gltf.materials.grass} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_StoneWall_0.geometry} material={gltf.materials.StoneWall} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_sandwall_0.geometry} material={gltf.materials.sandwall} />
          <T.Mesh
            geometry={gltf.nodes['island_basemodel_Grass-Sand_0'].geometry}
            material={gltf.materials['Grass-Sand']}
          />
          <T.Mesh
            geometry={gltf.nodes.island_basemodel_stone_pavement_0.geometry}
            material={gltf.materials.stone_pavement}
          />
        </T.Group>
        <T.Group position={[2465.02, 25.04, -188.92]} rotation={[0, 0.1, 0]} scale={10}>
          <T.Mesh geometry={gltf.nodes.island_basemodel_02_sandwall_0.geometry} material={gltf.materials.sandwall} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_02_cliff_0.geometry} material={gltf.materials.cliff} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_02_grass_0.geometry} material={gltf.materials.grass} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_02_sand_0.geometry} material={gltf.materials.sand} />
          <T.Mesh
            geometry={gltf.nodes['island_basemodel_02_Grass-Sand_0'].geometry}
            material={gltf.materials['Grass-Sand']}
          />
          <T.Mesh geometry={gltf.nodes.island_basemodel_02_StoneWall_0.geometry} material={gltf.materials.StoneWall} />
          <T.Mesh
            geometry={gltf.nodes.island_basemodel_02_stone_pavement_0.geometry}
            material={gltf.materials.stone_pavement}
          />
        </T.Group>
        <T.Group position={[2465.02, 25.04, -188.92]} rotation={[0, 0.1, 0]} scale={10}>
          <T.Mesh geometry={gltf.nodes.island_basemodel_03_sandwall_0.geometry} material={gltf.materials.sandwall} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_03_grass_0.geometry} material={gltf.materials.grass} />
          <T.Mesh
            geometry={gltf.nodes['island_basemodel_03_Grass-Sand_0'].geometry}
            material={gltf.materials['Grass-Sand']}
          />
        </T.Group>
        <T.Group position={[2465.02, 25.04, -188.92]} rotation={[0, 0.1, 0]} scale={10}>
          <T.Mesh geometry={gltf.nodes.island_basemodel_04_grass_0.geometry} material={gltf.materials.grass} />
          <T.Mesh geometry={gltf.nodes.island_basemodel_04_sandwall_0.geometry} material={gltf.materials.sandwall} />
          <T.Mesh
            geometry={gltf.nodes['island_basemodel_04_Grass-Sand_0'].geometry}
            material={gltf.materials['Grass-Sand']}
          />
        </T.Group>
        <T.Group position={[2465.02, 25.04, -188.92]} rotation={[0, 0.1, 0]} scale={10}>
          <T.Mesh geometry={gltf.nodes.island_cave_StoneWall_0.geometry} material={gltf.materials.StoneWall} />
          <T.Mesh
            geometry={gltf.nodes.island_cave_stone_pavement_0.geometry}
            material={gltf.materials.stone_pavement}
          />
          <T.Mesh geometry={gltf.nodes.island_cave_stone_arrow_0.geometry} material={gltf.materials.stone_arrow} />
          <T.Mesh geometry={gltf.nodes.island_cave_sandwall_0.geometry} material={gltf.materials.sandwall} />
        </T.Group>
        <T.Group position={[2465.02, 25.04, -188.92]} rotation={[0, 0.1, 0]} scale={10}>
          <T.Mesh geometry={gltf.nodes.rope_bridge_rope_bridge_0.geometry} material={gltf.materials.rope_bridge} />
          <T.Mesh
            geometry={gltf.nodes.rope_bridge_M_wooden_pillar_0.geometry}
            material={gltf.materials.M_wooden_pillar}
          />
        </T.Group>
        <T.Mesh
          geometry={gltf.nodes.island_fence_01_BambooFence_0.geometry}
          material={gltf.materials.BambooFence}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Mesh
          geometry={gltf.nodes.island_grasstrim_GrassTrim_0.geometry}
          material={gltf.materials.GrassTrim}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Mesh
          geometry={gltf.nodes.lavaflow_LavaNewFalling_0.geometry}
          material={gltf.materials.LavaNewFalling}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Mesh
          geometry={gltf.nodes.lava_LavaNew_0.geometry}
          material={gltf.materials.LavaNew}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Mesh
          geometry={gltf.nodes.island_water_01_waterMaterial_0.geometry}
          material={gltf.materials.waterMaterial}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Mesh
          geometry={gltf.nodes.island_water_02_waterMaterial_0.geometry}
          material={gltf.materials.waterMaterial}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Mesh
          geometry={gltf.nodes.island_water_03_waterMaterial_0.geometry}
          material={gltf.materials.waterMaterial}
          position={[2465.02, 25.04, -188.92]}
          rotation={[0, 0.1, 0]}
          scale={10}
        />
        <T.Group position={[951, 57.98, 740.42]} rotation={[0, -0.22, 0]} scale={[1, 28.69, 1]}>
          <T.Mesh geometry={gltf.nodes.Axe_M_wooden_rafter_0.geometry} material={gltf.materials.M_wooden_rafter} />
          <T.Mesh
            geometry={gltf.nodes.SwingingAxe_SwingingAxe_0.geometry}
            material={gltf.materials.SwingingAxe}
            position={[-0.09, -0.34, -0.01]}
            scale={[1, 0.03, 1]}
          />
          <T.Mesh
            geometry={gltf.nodes['SwingingAxe_(1)_SwingingAxe_0'].geometry}
            material={gltf.materials.SwingingAxe}
            position={[-0.09, -0.34, -0.01]}
            scale={[1, 0.03, 1]}
          />
        </T.Group>
        <T.Mesh
          geometry={gltf.nodes.Orca_Dolphin_0.geometry}
          material={gltf.materials.Dolphin}
          position={[613.24, 10.04, 1157.74]}
          rotation={[-Math.PI / 2, 0, 0.88]}
          scale={1.5}
        />
        <T.Mesh
          geometry={gltf.nodes['Orca_(1)_Dolphin_0'].geometry}
          material={gltf.materials.Dolphin}
          position={[792.14, 11.74, 594.08]}
          rotation={[-Math.PI / 2, 0, -2]}
          scale={1.5}
        />
      </T.Group>
      <T.Group position={[693, 0, 596]}>
        <T.Group position={[20.87, 141.36, 114.88]}>
          <T.Mesh
            geometry={gltf.nodes.BoostPad_BoostPadMaterial001_0.geometry}
            material={gltf.materials['BoostPadMaterial.001']}
            position={[-68.47, -136.42, 9.82]}
            rotation={[-Math.PI, 0.1, Math.PI]}
            scale={[5.56, 4.63, 8.02]}
          />
          <T.Mesh
            geometry={gltf.nodes['BoostPad_(1)_BoostPadMaterial001_0'].geometry}
            material={gltf.materials['BoostPadMaterial.001']}
            position={[121.47, -139.16, 313.12]}
            scale={[5.56, 4.63, 8.02]}
          />
          <T.Mesh
            geometry={gltf.nodes['BoostPad_(2)001_BoostPadMaterial001_0'].geometry}
            material={gltf.materials['BoostPadMaterial.001']}
            position={[121.4, -132.68, 310.22]}
            rotation={[0.06, 0, 0]}
            scale={[5.56, 4.63, 8.02]}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
