<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/assets/picnic.glb
Author: Esbosan (https://sketchfab.com/Esbosan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-picnic-ea1bac7de2094e46815e49bd533950c2
Title: Low Poly Picnic
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/assets/picnic.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene" scale={0.1}>
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="2d6abe53b49f4a54ad883fd54625c859fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="Camera001" position={[5.62, 183.3, 427.95]} rotation={[-0.37, -0.02, -0.01]}>
                <T.Group name="Object_71" />
              </T.Group>
              <T.Group name="tronco00" position={[-39.98, 21.95, -40.33]} rotation={[-Math.PI / 2, 0, -1.59]}>
                <T.Mesh
                  name="tronco00_mo_0"
                  geometry={gltf.nodes.tronco00_mo_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group
                name="arbol04"
                position={[-40.51, 36.22, -34.52]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[1, 0.88, 0.78]}
              >
                <T.Mesh
                  name="arbol04_lima_0"
                  geometry={gltf.nodes.arbol04_lima_0.geometry}
                  material={gltf.materials.lima}
                />
              </T.Group>
              <T.Group
                name="arbol00"
                position={[-46.37, 52.94, -41.1]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[1, 0.6, 0.78]}
              >
                <T.Mesh
                  name="arbol00_verde?c_0"
                  geometry={gltf.nodes['arbol00_verde?c_0'].geometry}
                  material={gltf.materials.verdec}
                />
              </T.Group>
              <T.Group
                name="arbol01"
                position={[-46.58, 59.32, -28.79]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[1, 0.34, 0.36]}
              >
                <T.Mesh
                  name="arbol01_lima_0"
                  geometry={gltf.nodes.arbol01_lima_0.geometry}
                  material={gltf.materials.lima}
                />
              </T.Group>
              <T.Group
                name="arbol02"
                position={[-42.3, 66.79, -34.55]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[1, 0.56, 0.36]}
              >
                <T.Mesh
                  name="arbol02_verde?c_0"
                  geometry={gltf.nodes['arbol02_verde?c_0'].geometry}
                  material={gltf.materials.verdec}
                />
              </T.Group>
              <T.Group
                name="arbol03"
                position={[-42.3, 71.93, -34.55]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[0.37, 0.36, 0.27]}
              >
                <T.Mesh
                  name="arbol03_lima_0"
                  geometry={gltf.nodes.arbol03_lima_0.geometry}
                  material={gltf.materials.lima}
                />
              </T.Group>
              <T.Group
                name="rocas02"
                position={[-25.05, 5.45, 47.14]}
                rotation={[-1.57, 0.05, -1.59]}
                scale={[1, 0.88, 0.78]}
              >
                <T.Mesh
                  name="rocas02_marron_0"
                  geometry={gltf.nodes.rocas02_marron_0.geometry}
                  material={gltf.materials.marron}
                />
              </T.Group>
              <T.Group
                name="rocas00"
                position={[-8.32, 13.13, 47.43]}
                rotation={[-1.63, 0.2, -1.34]}
                scale={[0.28, 0.24, 0.21]}
              >
                <T.Mesh
                  name="rocas00_mo_0"
                  geometry={gltf.nodes.rocas00_mo_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group
                name="rocas01"
                position={[-32.27, 33.86, 48.49]}
                rotation={[-1.57, -0.05, -1.59]}
                scale={[1, 0.6, 0.78]}
              >
                <T.Mesh
                  name="rocas01_mo_0"
                  geometry={gltf.nodes.rocas01_mo_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group name="tronco01" position={[55.71, 7.72, -25.75]} rotation={[-3.14, -0.31, -1.56]}>
                <T.Group name="Object_23" position={[0, 0, -45.58]}>
                  <T.Mesh
                    name="tronco01_crema_0"
                    geometry={gltf.nodes.tronco01_crema_0.geometry}
                    material={gltf.materials.crema}
                  />
                  <T.Mesh
                    name="tronco01_mm_0"
                    geometry={gltf.nodes.tronco01_mm_0.geometry}
                    material={gltf.materials.material_5}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="mantel00" position={[24.21, -1.83, -0.65]} rotation={[-Math.PI / 2, 0, -1.59]} scale={0.8}>
                <T.Mesh
                  name="mantel00_rojo_0"
                  geometry={gltf.nodes.mantel00_rojo_0.geometry}
                  material={gltf.materials.rojo}
                />
                <T.Mesh
                  name="mantel00_blanco_0"
                  geometry={gltf.nodes.mantel00_blanco_0.geometry}
                  material={gltf.materials.blanco}
                />
              </T.Group>
              <T.Group name="cosas_picnic01" position={[42.26, 13.77, -13.99]} rotation={[-Math.PI / 2, 0, -1.59]}>
                <T.Group name="Object_30" position={[66.77, 31.01, -15.6]}>
                  <T.Mesh
                    name="cosas_picnic01_crema_0"
                    geometry={gltf.nodes.cosas_picnic01_crema_0.geometry}
                    material={gltf.materials.crema}
                  />
                  <T.Mesh
                    name="cosas_picnic01_verde?c_0"
                    geometry={gltf.nodes['cosas_picnic01_verde?c_0'].geometry}
                    material={gltf.materials.verdec}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="sopa01" position={[31.44, 4.3, 7.03]} rotation={[-Math.PI / 2, 0, -1.59]} scale={0.65}>
                <T.Group name="Object_34" position={[84.59, 45.36, -9.38]}>
                  <T.Mesh
                    name="sopa01_blanco_0"
                    geometry={gltf.nodes.sopa01_blanco_0.geometry}
                    material={gltf.materials.blanco}
                  />
                  <T.Mesh
                    name="sopa01_mm_0"
                    geometry={gltf.nodes.sopa01_mm_0.geometry}
                    material={gltf.materials.material_5}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="sopa00" position={[45.31, -1.83, 50.9]} rotation={[-Math.PI / 2, 0, -1.59]} scale={0.65}>
                <T.Mesh
                  name="sopa00_blanco_0"
                  geometry={gltf.nodes.sopa00_blanco_0.geometry}
                  material={gltf.materials.blanco}
                />
                <T.Mesh
                  name="sopa00_mm_0"
                  geometry={gltf.nodes.sopa00_mm_0.geometry}
                  material={gltf.materials.material_5}
                />
              </T.Group>
              <T.Group name="salsas00" position={[37.17, 2.11, 15.79]} rotation={[-Math.PI / 2, 0, -1.59]} scale={0.57}>
                <T.Mesh
                  name="salsas00_Material_#59_0"
                  geometry={gltf.nodes['salsas00_Material_#59_0'].geometry}
                  material={gltf.materials.Material_59}
                />
              </T.Group>
              <T.Group name="salsas01" position={[40.64, 2.11, 15.85]} rotation={[-Math.PI / 2, 0, -1.59]} scale={0.57}>
                <T.Mesh
                  name="salsas01_blanco_0"
                  geometry={gltf.nodes.salsas01_blanco_0.geometry}
                  material={gltf.materials.blanco}
                />
              </T.Group>
              <T.Group name="bote00" position={[60.02, -1.83, 41.87]} rotation={[-Math.PI / 2, 0, -1.59]}>
                <T.Mesh
                  name="bote00_mo_0"
                  geometry={gltf.nodes.bote00_mo_0.geometry}
                  material={gltf.materials.material}
                />
                <T.Mesh
                  name="bote00_Material_#59_0"
                  geometry={gltf.nodes['bote00_Material_#59_0'].geometry}
                  material={gltf.materials.Material_59}
                />
                <T.Mesh
                  name="bote00_rojo_0"
                  geometry={gltf.nodes.bote00_rojo_0.geometry}
                  material={gltf.materials.rojo}
                />
                <T.Mesh
                  name="bote00_blanco_0"
                  geometry={gltf.nodes.bote00_blanco_0.geometry}
                  material={gltf.materials.blanco}
                />
              </T.Group>
              <T.Group
                name="vaso00"
                position={[22.77, 4.2, -14.04]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[0.67, 0.67, 1.26]}
              >
                <T.Group name="Object_50" position={[48.18, 18.58, -4.77]}>
                  <T.Mesh
                    name="vaso00_blanco_0"
                    geometry={gltf.nodes.vaso00_blanco_0.geometry}
                    material={gltf.materials.blanco}
                  />
                  <T.Mesh
                    name="vaso00_Material_#59_0"
                    geometry={gltf.nodes['vaso00_Material_#59_0'].geometry}
                    material={gltf.materials.Material_59}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="vaso01"
                position={[34.37, -1.83, 38.92]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[0.67, 0.67, 1.26]}
              >
                <T.Mesh
                  name="vaso01_blanco_0"
                  geometry={gltf.nodes.vaso01_blanco_0.geometry}
                  material={gltf.materials.blanco}
                />
                <T.Mesh
                  name="vaso01_Material_#59_0"
                  geometry={gltf.nodes['vaso01_Material_#59_0'].geometry}
                  material={gltf.materials.Material_59}
                />
              </T.Group>
              <T.Group name="cosas_picnic00" position={[7.68, 2.31, 8.29]} rotation={[-Math.PI / 2, 0, -1.59]}>
                <T.Mesh
                  name="cosas_picnic00_crema_0"
                  geometry={gltf.nodes.cosas_picnic00_crema_0.geometry}
                  material={gltf.materials.crema}
                />
              </T.Group>
              <T.Group
                name="queso00"
                position={[22.22, -1.83, 46.3]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[1, 1, 1.31]}
              >
                <T.Mesh
                  name="queso00_Material_#60_0"
                  geometry={gltf.nodes['queso00_Material_#60_0'].geometry}
                  material={gltf.materials.Material_60}
                />
              </T.Group>
              <T.Group name="Plane002" position={[10.24, 0, 35.01]} rotation={[-Math.PI / 2, 0, -1.59]} />
              <T.Group
                name="piedras02"
                position={[65.36, 1.82, 49.35]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[0.37, 0.22, 0.18]}
              >
                <T.Mesh
                  name="piedras02_Material_#61_0"
                  geometry={gltf.nodes['piedras02_Material_#61_0'].geometry}
                  material={gltf.materials.Material_61}
                />
              </T.Group>
              <T.Group
                name="piedras00"
                position={[49.76, 1.82, 60.41]}
                rotation={[-Math.PI / 2, 0, -2.52]}
                scale={[0.09, 0.13, 0.1]}
              >
                <T.Mesh
                  name="piedras00_Material_#61_0"
                  geometry={gltf.nodes['piedras00_Material_#61_0'].geometry}
                  material={gltf.materials.Material_61}
                />
              </T.Group>
              <T.Group
                name="piedras01"
                position={[62.98, 1.82, 62.63]}
                rotation={[-Math.PI / 2, 0, -1.61]}
                scale={[0.09, 0.07, 0.1]}
              >
                <T.Mesh
                  name="piedras01_Material_#61_0"
                  geometry={gltf.nodes['piedras01_Material_#61_0'].geometry}
                  material={gltf.materials.Material_61}
                />
              </T.Group>
              <T.Group name="cesped" position={[12.12, -0.49, -2.66]} rotation={[-Math.PI / 2, 0, -1.59]}>
                <T.Mesh
                  name="cesped_verde?c_0"
                  geometry={gltf.nodes['cesped_verde?c_0'].geometry}
                  material={gltf.materials.verdec_0}
                />
              </T.Group>
              <T.Group
                name="Circle001"
                position={[11.59, 183.3, -6.64]}
                rotation={[-Math.PI / 2, 0, -1.59]}
                scale={[4.35, 4.35, 4.3]}
              />
              <T.Group name="Camera001Target" position={[13.64, 15.2, -1.1]} />
              <T.Group name="Compass001" position={[20.69, 101.7, -84.09]} rotation={[-1.84, 0.16, 0]}>
                <T.Group name="Daylight001" position={[29.1, -177.16, 690.67]} rotation={[0.25, 0.04, 0.16]}>
                  <T.Group name="Sun001" rotation={[Math.PI / 2, 0, 0]}>
                    <T.Group name="Object_76" rotation={[Math.PI / 2, 0, 0]}>
                      <T.Group name="Object_77" />
                    </T.Group>
                  </T.Group>
                  <T.Group name="Sky002" rotation={[Math.PI / 2, 0, 0]}>
                    <T.Group name="Object_79" rotation={[Math.PI / 2, 0, 0]}>
                      <T.Group name="Object_80" />
                    </T.Group>
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
