<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/assets/randomness.glb
Author: 1catalogue (https://sketchfab.com/1catalogue)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/randomness-dd376218653a44b4818ae8dc2becfe5f
Title: Randomness
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/assets/randomness.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <T.Group name="Root">
          <T.Group name="Camera" position={[0.99, -0.82, 0.73]} rotation={[2.65, -0.58, 2.55]} scale={-0.85} />
          <T.Group name="Icosahedron_65" position={[0.1, -0.05, 0.1]} rotation={[0, 0, -Math.PI]} scale={-0.85}>
            <T.Mesh
              name="Icosahedron_65_0"
              geometry={gltf.nodes.Icosahedron_65_0.geometry}
              material={gltf.materials.Default}
            />
          </T.Group>
          <T.Group name="Lamp" position={[0.58, 0.07, 0.8]} rotation={[-0.74, 0.12, -2.33]} scale={-0.85}>
            <T.Group name="Lamp_1" />
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
